server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://share:share@localhost:8761/eureka/ #注册到刚才那台Eureka Server地址
spring:
  application:
    name: share-controller
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    ##全局方法使用default
    HelloClient#toHello():
      execution:
        isolation:
          thread:
            ##超时时间
            timeoutInMilliseconds: 500
      circuitBreaker:
        ##每秒3次请求
        requestVolumeThreshold: 3

