spring:
  application:
    name: eureka-server
  security:
    user:
      name: share
      password: share
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 2000
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


